node {
	    // reference to maven
	    // ** NOTE: This 'Maven3.6.3' Maven tool must be configured in the Jenkins Global Configuration.   
	    def mvnHome = tool 'Maven3.6.3'
	

	    // holds reference to docker image
	    def dockerImage
	    // ip address of the docker private repository(nexus)
	 
	    def dockerImageTag = "hello-world-example${env.BUILD_NUMBER}"
	    
	    stage('Clone Repo') { // for display purposes
	      // Get some code from a GitHub repository
	      git 'https://github.com/hmiliev/tests.git'
	      // Get the Maven tool.
	      // ** NOTE: This tool 'Maven3.6.3' Maven tool must be configured
	      // **       in the global configuration.           
	      mvnHome = tool 'Maven3.6.3'
	    }    
	  
	    stage('Build Project') {
	      // build project via maven
	      sh "'${mvnHome}/bin/mvn' clean install -f hello-world"
	    }
			
	    stage('Build Docker Image') {
	      // build docker image
	      dockerImage = docker.build("hello-world-example:${env.BUILD_NUMBER}", "hello-world")
	    }
	   
	    stage('Deploy Docker Image'){
	      
	      // deploy docker image to nexus
			
	      echo "Docker Image Tag Name: ${dockerImageTag}"
		  
		  sh "docker stop hello-world-example"
		  
		  sh "docker rm hello-world-example"
		  
		  sh "docker run --name hello-world-example -d -p 2222:2222 hello-world-example:${env.BUILD_NUMBER}"
		  
		  // docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
	      //    dockerImage.push("${env.BUILD_NUMBER}")
	      //      dockerImage.push("latest")
	      //  }
	    }      
}